[package]
name = "ppp"
version = "0.1.0"
edition = "2021"

[dependencies]
mlogv32 = { path = "../mlogv32" }
ppproto = "0.2.1"

[profile.dev]

[profile.release]
panic = "abort"
# values: 2, 3, s, z
opt-level = 3
overflow-checks = false
lto = true
