repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
        exclude: |
          (?x)^(
            \.vscode/.+\.json
            | .*devcontainer\.json
          )$
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude_types: [rust]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
