[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "target-feature=-c",
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]

[alias]
rbuild = "build --release"
rb = "rbuild"
