templates:
  controller: controller.mlog.jinja
  worker: worker.mlog.jinja

schematics:
  lookups: ../../schematics/lookup_procs.msch
  ram: ../../schematics/ram_proc.msch

instructions:
  - label: BEQ
    cost: 2
  - label: BNE
    cost: 2
  - label: JAL
    cost: 1 + 9
  - label: JALR
    cost: 3 + 8
  - label: BLT
    cost: 2 + 5 + 2
  - label: BGE
    cost: 2 + 5 + 1
  - label: BLTU
    cost: 2
  - label: BGEU
    cost: 1
  - label: LB
    cost: 3 + 29
  - label: LH
    cost: 3 + 29
  - label: LW
    cost: 3 + 29
  - label: LUI
    cost: 2
  - label: LBU
    cost: 3 + 29
  - label: LHU
    cost: 2 + 29
  - label: SB
    cost: 2 + 28
  - label: SH
    cost: 2 + 28
  - label: SW
    cost: 1 + 28
  - label: AMOADD.W
    cost: 2 + 52
  - label: AMOSWAP.W
    cost: 1 + 52
  - label: LR.W
    cost: 8 + 8 + 32
  - label: SC.W
    cost: 7 + 8
  - label: AMOXOR.W
    cost: 2 + 52
  - label: AMOOR.W
    cost: 2 + 52
  - label: AMOAND.W
    cost: 2 + 52
  - label: AMOMIN.W
    cost: 2 + 57
  - label: AMOMAX.W
    cost: 2 + 57
  - label: AMOMINU.W
    cost: 2 + 52
  - label: AMOMAXU.W
    cost: 2 + 52
  - label: ADDI
    cost: 3
  - label: SUB
    cost: 2 + 1 + 3
  - label: SLTI
    cost: 1 + 2 + 5 + 1 + 2
  - label: SLTIU
    cost: 2
  - label: XORI
    cost: 2
  - label: SRA
    cost: 1 + 5 + 6
  - label: ORI
    cost: 2
  - label: ANDI
    cost: 2
  - label: ADD
    cost: 1 + 3
  - label: SLL
    cost: 1 + 5
  - label: SLT
    cost: 2 + 5 + 1 + 2
  - label: SLTU
    cost: 1 + 2
  - label: XOR
    cost: 1 + 2
  - label: SRL
    cost: 1 + 2
  - label: OR
    cost: 1 + 2
  - label: AND
    cost: 1 + 2
  - label: MUL
    cost: 7 + 9
  - label: MULH
    cost: 2 + 13
  - label: MULHSU
    cost: 3 + 13
  - label: MULHU
    cost: 3 + 13
  - label: DIV
    cost: 2 + 5 + 5
  - label: DIVU
    cost: 5
  - label: REM
    cost: 2 + 5 + 5
  - label: REMU
    cost: 5
  - label: PRIV
    cost: 5
  - label: CSRRW
    cost: 2 + 60 # probably an overestimate, but the CSR code is very complicated
  - label: CSRRS
    cost: 2 + 60
  - label: CSRRC
    cost: 1 + 60
  - label: AUIPC
    cost: 3
  - label: CSRRWI
    cost: 1 + 2 + 60
  - label: CSRRSI
    cost: 1 + 2 + 60
  - label: CSRRCI
    cost: 1 + 1 + 60
  - label: FENCE
    cost: 1
  - label: SLLI
    cost: 5
  - label: SRLI
    cost: 2
  - label: SRAI
    cost: 5 + 6
  - label: ILLEGAL_OP
    cost: 0
  - label: MLOGSYS
    cost: 5
  - label: MLOGDRAW
    cost: 16
