templates:
  controller: controller.mlog.jinja
  worker: worker.mlog.jinja

schematics:
  lookups: ../../schematics/lookup_procs.msch
  ram: ../../schematics/ram_proc.msch

configs: ../config/configs.yaml

instructions:
  - label: BEQ
  - label: BNE
  - label: JAL
  - label: JALR
  - label: BLT
  - label: BGE
  - label: BLTU
  - label: BGEU
  - label: LB
  - label: LH
  - label: LW
  - label: LUI
  - label: LBU
  - label: LHU
  - label: SB
  - label: SH
  - label: SW
  - label: AMOADD.W
  - label: AMOSWAP.W
  - label: LR.W
  - label: SC.W
  - label: AMOXOR.W
  - label: AMOOR.W
  - label: AMOAND.W
  - label: AMOMIN.W
  - label: AMOMAX.W
  - label: AMOMINU.W
  - label: AMOMAXU.W
  - label: ADDI
  - label: SUB
  - label: SLTI
  - label: SLTIU
  - label: XORI
  - label: SRA
  - label: ORI
  - label: ANDI
  - label: ADD
  - label: SLL
  - label: SLT
  - label: SLTU
  - label: XOR
  - label: SRL
  - label: OR
  - label: AND
  - label: MUL
  - label: MULH
  - label: MULHSU
  - label: MULHU
  - label: DIV
  - label: DIVU
  - label: REM
  - label: REMU
  - label: PRIV
  - label: CSRRW
  - label: CSRRS
  - label: CSRRC
  - label: AUIPC
  - label: CSRRWI
  - label: CSRRSI
  - label: CSRRCI
  - label: FENCE
  - label: SLLI
  - label: SRLI
  - label: SRAI
  - label: ILLEGAL_OP
  - label: MLOGSYS
