[package]
name = "mlogv32"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.7.0"
riscv = "0.12.1"
riscv-rt = { version = "0.15.0", features = ["pre-init", "single-hart"] }
uart = "2.1.1"

[features]
default = ["panic-handler"]
panic-handler = []
default-memory = ["riscv-rt/memory"]
