/* included with feature default-memory */

MEMORY {
    ROM  (rx)  : ORIGIN = 0x00000000, LENGTH = 512K
    RAM  (rwx) : ORIGIN = 0x80000000, LENGTH = 3M
}

REGION_ALIAS("REGION_TEXT",   ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA",   RAM);
REGION_ALIAS("REGION_BSS",    RAM);
REGION_ALIAS("REGION_HEAP",   RAM);
REGION_ALIAS("REGION_STACK",  RAM);

PROVIDE(_stack_size = 4K);
