template: base.mlog.jinja

defaults:
  BREAKPOINT_ADDRESS: '0x'
  UART_FIFO_CAPACITY: 253

configs:
  riscv-arch-test:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -40
    MEMORY_WIDTH: 32
    ROM_ROWS: 9
    RAM_ROWS: 9
    ICACHE_ROWS: 6

  micro:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -32
    MEMORY_WIDTH: 16
    ROM_ROWS: 2
    RAM_ROWS: 12
    ICACHE_ROWS: 2
  
  micropython:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -19
    MEMORY_WIDTH: 32
    ROM_ROWS: 1
    RAM_ROWS: 1
    ICACHE_ROWS: 1
