template: base.mlog.jinja

defaults:
  TARGET_IPT: 500000
  BREAKPOINT_ADDRESS: '0x'

configs:
  riscv-arch-test:
    MEMORY_X_OFFSET: -11
    MEMORY_Y_OFFSET: -26
    MEMORY_WIDTH: 32
    ROM_ROWS: 9
    RAM_ROWS: 9
    ICACHE_ROWS: 6
    UART_FIFO_CAPACITY: 253
  webserver:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -23
    MEMORY_WIDTH: 32
    ROM_ROWS: 1
    RAM_ROWS: 19
    ICACHE_ROWS: 1
    UART_FIFO_CAPACITY: 253
