template: base.mlog.jinja

defaults:
  UART_FIFO_CAPACITY: 253
  DATA_ROM_ROWS: 0

configs:
  riscv-arch-test:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -61
    MEMORY_WIDTH: 64
    PROGRAM_ROM_ROWS: 2
    DATA_ROM_ROWS: 18
    RAM_ROWS: 21
    ICACHE_ROWS: 4

  micro:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -32
    MEMORY_WIDTH: 16
    PROGRAM_ROM_ROWS: 2
    RAM_ROWS: 12
    ICACHE_ROWS: 2

  micropython:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -19
    MEMORY_WIDTH: 32
    PROGRAM_ROM_ROWS: 1
    RAM_ROWS: 1
    ICACHE_ROWS: 1

  linux:
    MEMORY_X_OFFSET: -9
    MEMORY_Y_OFFSET: -80
    MEMORY_WIDTH: 64
    PROGRAM_ROM_ROWS: 16
    RAM_ROWS: 16
    ICACHE_ROWS: 32
