[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "target-feature=-c",
]

[unstable]
build-std = ["core", "compiler_builtins"]

[alias]
rbuild = "build --release"
rb = "rbuild"

rsize = "size --release"

robjdump = [
    "objdump",
    "--release",
    "--",
    "--disassemble",
    "--no-show-raw-insn",
]
rod = "robjdump"

robjcopy = [
    "objcopy",
    "--release",
    "--",
    "--output-target", "binary",
]
