start: (line? _NEWLINE)*

?line: LABEL -> label
     | statement
     | directive

statement: TOKEN (TOKEN | LABEL_REF | LABEL | STRING)*

directive: _DIRECTIVE /assert_counter|(start|end)_(fetch|assert_length)|(push|pop)_saved/ TOKEN*

STRING.2: /"[^\n]*"/

LABEL.1: TOKEN ":"

LABEL_REF.1: "%" TOKEN "%"

TOKEN: /[^\n #\t;]+/

_DIRECTIVE.1: "#directive"

COMMENT: /#[^\n]*/

_NEWLINE: /[\n;]+/

%ignore /[ \t]+/
%ignore COMMENT
